# Generated by Django 3.0 on 2020-06-21 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='publish', max_length=20),
        ),
    ]
