# Generated by Django 3.0 on 2020-06-22 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_posts', '0003_auto_20200621_2248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='publish', max_length=20),
        ),
    ]
